/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Nasabah;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

/**
 *
 * @author septiandrd
 */
public class AppGUI extends javax.swing.JFrame {

    /**
     * Creates new form AppGUI
     */
    public AppGUI() {
        initComponents();
        panelMenu.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelLogin = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxUsername = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        jtxPass = new javax.swing.JPasswordField();
        panelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        btnAkun = new javax.swing.JButton();
        btnRiwayat = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnBayar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txHeader = new javax.swing.JLabel();
        panelTransfer = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtxRekTujuan = new javax.swing.JTextField();
        jtxJumlahTrf = new javax.swing.JTextField();
        btnProsesTrf = new javax.swing.JButton();
        btnBackTrf = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        panelPembayaran = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jboxPembayaran = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jtxJumlahBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnProsesBayar = new javax.swing.JButton();
        btnBackBayar = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        panelInfoAkun = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txNama = new javax.swing.JTextPane();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txUsername = new javax.swing.JTextPane();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txNoRek = new javax.swing.JTextPane();
        jLabel19 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txSaldo = new javax.swing.JTextPane();
        btnOkInfo = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        panelRiwayat = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        txAreaTrf = new javax.swing.JTextArea();
        btnOkRiwayat = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        txAreaBayar = new javax.swing.JTextArea();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        panelPembelian = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jboxPembayaran1 = new javax.swing.JComboBox<>();
        jLabel27 = new javax.swing.JLabel();
        jtxJumlahBayar1 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        btnProsesBayar1 = new javax.swing.JButton();
        btnBackBayar1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 50));
        setMaximumSize(new java.awt.Dimension(1000, 800));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel1.setText("  Login");

        jLabel2.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jtxUsername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxUsername.setPreferredSize(new java.awt.Dimension(5, 21));
        jtxUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxUsernameActionPerformed(evt);
            }
        });
        jtxUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtxUsernameKeyPressed(evt);
            }
        });

        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        jtxPass.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtxPass.setPreferredSize(new java.awt.Dimension(5, 21));

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(47, 47, 47)
                        .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtxUsername, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtxPass, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelLoginLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1))
                    .addComponent(btnLogin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(262, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtxPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnLogin)
                .addContainerGap(149, Short.MAX_VALUE))
        );

        getContentPane().add(panelLogin, "card2");

        panelMenu.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridLayout(2, 0));

        btnAkun.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        btnAkun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/People_group_users_friends_man_user_vector.png"))); // NOI18N
        btnAkun.setText("  Informasi Akun");
        jPanel1.add(btnAkun);

        btnRiwayat.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        btnRiwayat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/clock-event-history-schedule-time-icon--19.png"))); // NOI18N
        btnRiwayat.setText(" Riwayat Transaksi");
        jPanel1.add(btnRiwayat);

        btnTransfer.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        btnTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/momey_exchange-512 (1).png"))); // NOI18N
        btnTransfer.setText("Transfer");
        jPanel1.add(btnTransfer);

        btnBayar.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        btnBayar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/6000244544002.png"))); // NOI18N
        btnBayar.setText("   Pembayaran");
        jPanel1.add(btnBayar);

        jButton1.setFont(new java.awt.Font("Noto Sans", 1, 15)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/credit-card.png"))); // NOI18N
        jButton1.setText("    Pembelian");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);

        btnLogout.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/restart-1.png"))); // NOI18N
        btnLogout.setText("  Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogout);

        txHeader.setFont(new java.awt.Font("Noto Sans", 1, 20)); // NOI18N
        txHeader.setText("Welcome");

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(34, 34, 34)
                        .addComponent(txHeader))
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 691, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 58, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(txHeader)
                        .addGap(52, 52, 52)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(76, Short.MAX_VALUE))
        );

        getContentPane().add(panelMenu, "card3");

        jLabel11.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel11.setText("  Transfer");

        jLabel12.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel12.setText("No. Rekening Tujuan");

        jLabel13.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel13.setText("Jumlah Transfer");

        btnProsesTrf.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnProsesTrf.setText("Proses");

        btnBackTrf.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnBackTrf.setText("Back");

        javax.swing.GroupLayout panelTransferLayout = new javax.swing.GroupLayout(panelTransfer);
        panelTransfer.setLayout(panelTransferLayout);
        panelTransferLayout.setHorizontalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTransferLayout.createSequentialGroup()
                .addContainerGap(246, Short.MAX_VALUE)
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransferLayout.createSequentialGroup()
                        .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelTransferLayout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel11))
                            .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(panelTransferLayout.createSequentialGroup()
                                    .addComponent(btnBackTrf, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnProsesTrf, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jtxJumlahTrf)
                                .addComponent(jtxRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(244, 244, 244))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransferLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(260, 260, 260))))
        );
        panelTransferLayout.setVerticalGroup(
            panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTransferLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxRekTujuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxJumlahTrf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelTransferLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProsesTrf)
                    .addComponent(btnBackTrf))
                .addGap(85, 85, 85))
        );

        getContentPane().add(panelTransfer, "card5");

        jLabel6.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/credit-card.png"))); // NOI18N
        jLabel6.setText("  Pembelian");

        jLabel7.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel7.setText("Pilih Pembelian");

        jboxPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Pilih Pembelian>", "Listrik", "Air/PAM", "TV/Internet Berlangganan" }));

        jLabel8.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel8.setText("Nominal");

        jLabel9.setText("Rp.");

        btnProsesBayar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnProsesBayar.setText("Proses");

        btnBackBayar.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnBackBayar.setText("Back");

        javax.swing.GroupLayout panelPembayaranLayout = new javax.swing.GroupLayout(panelPembayaran);
        panelPembayaran.setLayout(panelPembayaranLayout);
        panelPembayaranLayout.setHorizontalGroup(
            panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembayaranLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jboxPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPembayaranLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelPembayaranLayout.createSequentialGroup()
                            .addComponent(btnBackBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProsesBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPembayaranLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel6))
                    .addGroup(panelPembayaranLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        panelPembayaranLayout.setVerticalGroup(
            panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembayaranLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel10)
                .addGap(46, 46, 46)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jboxPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxJumlahBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(28, 28, 28)
                .addGroup(panelPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProsesBayar)
                    .addComponent(btnBackBayar))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(panelPembayaran, "card4");

        jLabel15.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel15.setText("Informasi Akun");

        jLabel16.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel16.setText("Nama");

        txNama.setEditable(false);
        txNama.setDisabledTextColor(new java.awt.Color(1, 1, 1));
        jScrollPane1.setViewportView(txNama);

        jLabel17.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel17.setText("Username");

        txUsername.setEditable(false);
        jScrollPane2.setViewportView(txUsername);

        jLabel18.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel18.setText("No. Rekening");

        txNoRek.setEditable(false);
        jScrollPane3.setViewportView(txNoRek);

        jLabel19.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel19.setText("Saldo");

        txSaldo.setEditable(false);
        jScrollPane4.setViewportView(txSaldo);

        btnOkInfo.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnOkInfo.setText("OK");

        javax.swing.GroupLayout panelInfoAkunLayout = new javax.swing.GroupLayout(panelInfoAkun);
        panelInfoAkun.setLayout(panelInfoAkunLayout);
        panelInfoAkunLayout.setHorizontalGroup(
            panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoAkunLayout.createSequentialGroup()
                .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInfoAkunLayout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInfoAkunLayout.createSequentialGroup()
                                .addGap(64, 64, 64)
                                .addComponent(jLabel15))
                            .addGroup(panelInfoAkunLayout.createSequentialGroup()
                                .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19))
                                .addGap(26, 26, 26)
                                .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnOkInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelInfoAkunLayout.createSequentialGroup()
                        .addGap(263, 263, 263)
                        .addComponent(jLabel20)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        panelInfoAkunLayout.setVerticalGroup(
            panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInfoAkunLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel20)
                .addGap(24, 24, 24)
                .addComponent(jLabel15)
                .addGap(18, 18, 18)
                .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(panelInfoAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(18, 18, 18)
                .addComponent(btnOkInfo)
                .addGap(68, 68, 68))
        );

        getContentPane().add(panelInfoAkun, "card6");

        jLabel21.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel21.setText(" History");

        txAreaTrf.setEditable(false);
        txAreaTrf.setColumns(20);
        txAreaTrf.setRows(5);
        jScrollPane5.setViewportView(txAreaTrf);

        btnOkRiwayat.setFont(new java.awt.Font("Noto Sans", 1, 14)); // NOI18N
        btnOkRiwayat.setText("OK");

        txAreaBayar.setEditable(false);
        txAreaBayar.setColumns(20);
        txAreaBayar.setRows(5);
        jScrollPane6.setViewportView(txAreaBayar);

        jLabel23.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel23.setText("Riwayat Transfer");

        jLabel24.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel24.setText("Riwayat Pembayaran");

        javax.swing.GroupLayout panelRiwayatLayout = new javax.swing.GroupLayout(panelRiwayat);
        panelRiwayat.setLayout(panelRiwayatLayout);
        panelRiwayatLayout.setHorizontalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRiwayatLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnOkRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelRiwayatLayout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(31, 31, 31)
                        .addComponent(jLabel21)
                        .addGap(288, 288, 288))
                    .addGroup(panelRiwayatLayout.createSequentialGroup()
                        .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRiwayatLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRiwayatLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(221, 221, 221)))
                        .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        panelRiwayatLayout.setVerticalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRiwayatLayout.createSequentialGroup()
                .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRiwayatLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel22))
                    .addGroup(panelRiwayatLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel21)))
                .addGap(18, 18, 18)
                .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnOkRiwayat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(panelRiwayat, "card7");

        jLabel25.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/credit-card.png"))); // NOI18N
        jLabel25.setText("  Pembelian");

        jLabel26.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel26.setText("Pilih Pembelian");

        jboxPembayaran1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Pilih Pembelian>", "Listrik", "Air/PAM", "TV/Internet Berlangganan" }));

        jLabel27.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        jLabel27.setText("Nominal");

        jLabel28.setText("Rp.");

        btnProsesBayar1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnProsesBayar1.setText("Proses");

        btnBackBayar1.setFont(new java.awt.Font("Noto Sans", 0, 14)); // NOI18N
        btnBackBayar1.setText("Back");

        javax.swing.GroupLayout panelPembelianLayout = new javax.swing.GroupLayout(panelPembelian);
        panelPembelian.setLayout(panelPembelianLayout);
        panelPembelianLayout.setHorizontalGroup(
            panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembelianLayout.createSequentialGroup()
                .addGap(244, 244, 244)
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jboxPembayaran1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPembelianLayout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jtxJumlahBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(panelPembelianLayout.createSequentialGroup()
                            .addComponent(btnBackBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProsesBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelPembelianLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel25))
                    .addGroup(panelPembelianLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel29)))
                .addContainerGap(245, Short.MAX_VALUE))
        );
        panelPembelianLayout.setVerticalGroup(
            panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembelianLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel29)
                .addGap(46, 46, 46)
                .addComponent(jLabel25)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jboxPembayaran1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxJumlahBayar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel28))
                .addGap(28, 28, 28)
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProsesBayar1)
                    .addComponent(btnBackBayar1))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        getContentPane().add(panelPembelian, "card4");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxUsernameActionPerformed
    }//GEN-LAST:event_jtxUsernameActionPerformed

    private void jtxUsernameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxUsernameKeyPressed
    }//GEN-LAST:event_jtxUsernameKeyPressed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AppGUI().setVisible(true);       
            }
        });
    }

    public JButton getBtnAkun() {
        return btnAkun;
    }

    public JButton getBtnBackBayar() {
        return btnBackBayar;
    }

    public JButton getBtnBackTrf() {
        return btnBackTrf;
    }

    public JButton getBtnBayar() {
        return btnBayar;
    }

    public JButton getBtnLogin() {
        return btnLogin;
    }

    public JButton getBtnLogout() {
        return btnLogout;
    }

    public JButton getBtnOkInfo() {
        return btnOkInfo;
    }

    public JButton getBtnOkRiwayat() {
        return btnOkRiwayat;
    }

    public JButton getBtnProsesBayar() {
        return btnProsesBayar;
    }

    public JButton getBtnProsesTrf() {
        return btnProsesTrf;
    }

    public JButton getBtnRiwayat() {
        return btnRiwayat;
    }

    public JButton getBtnTransfer() {
        return btnTransfer;
    }

    public Double getJumlahBayar() {
        if (!jtxJumlahBayar.getText().isEmpty()) {
            return Double.parseDouble(jtxJumlahBayar.getText());
        } else {
            return 0.0;
        }            
    }

    public Double getJumlahTrf() {
        if (!jtxJumlahTrf.getText().isEmpty()) {
            return Double.parseDouble(jtxJumlahTrf.getText());
        } else {
            return 0.0;
        }            
    }

    public String getJtxPass() {
        return jtxPass.getText();
    }

    public String getRekTujuan() {
        return jtxRekTujuan.getText();
    }

    public String getJtxUsername() {
        return jtxUsername.getText();
    }
    
    public String getPembayaran() {
        return jboxPembayaran.getSelectedItem().toString();
    }

    public void AddActionListener(ActionListener a) {
        btnAkun.addActionListener(a);
        btnBackBayar.addActionListener(a);
        btnBackTrf.addActionListener(a);
        btnBayar.addActionListener(a);
        btnLogin.addActionListener(a);
        btnLogout.addActionListener(a);
        btnOkInfo.addActionListener(a);
        btnOkRiwayat.addActionListener(a);
        btnProsesBayar.addActionListener(a);
        btnProsesTrf.addActionListener(a);
        btnRiwayat.addActionListener(a);
        btnTransfer.addActionListener(a);       
    }
    
    public void Login() {
        panelLogin.setVisible(true);
        panelMenu.setVisible(false);
        panelTransfer.setVisible(false);
        panelPembayaran.setVisible(false);
        panelInfoAkun.setVisible(false);
        panelRiwayat.setVisible(false);
    }
    
    public void Menu() {
        panelLogin.setVisible(false);
        panelMenu.setVisible(true);
        panelTransfer.setVisible(false);
        panelPembayaran.setVisible(false);
        panelInfoAkun.setVisible(false);
        panelRiwayat.setVisible(false);
    }
    
    public void Transfer() {
        panelLogin.setVisible(false);
        panelMenu.setVisible(false);
        panelTransfer.setVisible(true);
        panelPembayaran.setVisible(false);
        panelInfoAkun.setVisible(false);
        panelRiwayat.setVisible(false);
    }
    
    public void Pembayaran() {
        panelLogin.setVisible(false);
        panelMenu.setVisible(false);
        panelTransfer.setVisible(false);
        panelPembayaran.setVisible(true);
        panelInfoAkun.setVisible(false);
        panelRiwayat.setVisible(false);
    }
    
    public void InfoAkun(Nasabah n) {
        panelLogin.setVisible(false);
        panelMenu.setVisible(false);
        panelTransfer.setVisible(false);
        panelPembayaran.setVisible(false);
        panelInfoAkun.setVisible(true);
        panelRiwayat.setVisible(false);
        
        txNama.setText(n.getNama());
        txUsername.setText(n.getUsername());
        txNoRek.setText(n.getNorek());
        String s = "";
        String saldo = String.valueOf(n.getSaldo());
        int x=saldo.length()-2;
        for(int i=0; i<x; i++){
            if (x%3 != 0){
                s += saldo.substring(i, (x%3)) + "."; 
                i += (x%3)-1;
                x -= (x%3);
            } else {
                s += saldo.substring(i, i+3) + ".";
                i += 2;
            }                               
        }
        s = s.substring(0, (s.length()-1));
        txSaldo.setText("Rp. "+s+",-");        
    }
    
    public void Riwayat() {
        panelLogin.setVisible(false);
        panelMenu.setVisible(false);
        panelTransfer.setVisible(false);
        panelPembayaran.setVisible(false);
        panelInfoAkun.setVisible(false);
        panelRiwayat.setVisible(true);
    }
    
    public void resetLogin() {
        jtxUsername.setText("");
        jtxPass.setText("");
    }
    
    public void resetTransfer() {
        jtxRekTujuan.setText("");
        jtxJumlahTrf.setText("");
    }
    
    public void resetPembayaran() {
        jtxJumlahBayar.setText("");
        jboxPembayaran.setSelectedIndex(0);
    }    
    
    public void setTextRiwayatTrf(String text) {
        txAreaTrf.setText(text);
    }
    
    public void setTextRiwayatBayar(String text) {
        txAreaBayar.setText(text);
    }
    
    public void setHeader(String text) {
        txHeader.setText("Welcome, "+text+" !");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAkun;
    private javax.swing.JButton btnBackBayar;
    private javax.swing.JButton btnBackBayar1;
    private javax.swing.JButton btnBackTrf;
    private javax.swing.JButton btnBayar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnOkInfo;
    private javax.swing.JButton btnOkRiwayat;
    private javax.swing.JButton btnProsesBayar;
    private javax.swing.JButton btnProsesBayar1;
    private javax.swing.JButton btnProsesTrf;
    private javax.swing.JButton btnRiwayat;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JComboBox<String> jboxPembayaran;
    private javax.swing.JComboBox<String> jboxPembayaran1;
    private javax.swing.JTextField jtxJumlahBayar;
    private javax.swing.JTextField jtxJumlahBayar1;
    private javax.swing.JTextField jtxJumlahTrf;
    private javax.swing.JPasswordField jtxPass;
    private javax.swing.JTextField jtxRekTujuan;
    private javax.swing.JTextField jtxUsername;
    private javax.swing.JPanel panelInfoAkun;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPembayaran;
    private javax.swing.JPanel panelPembelian;
    private javax.swing.JPanel panelRiwayat;
    private javax.swing.JPanel panelTransfer;
    private javax.swing.JTextArea txAreaBayar;
    private javax.swing.JTextArea txAreaTrf;
    private javax.swing.JLabel txHeader;
    private javax.swing.JTextPane txNama;
    private javax.swing.JTextPane txNoRek;
    private javax.swing.JTextPane txSaldo;
    private javax.swing.JTextPane txUsername;
    // End of variables declaration//GEN-END:variables
}
